# Generated by Django 6.0.5 on 2026-05-20 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fotografia',
            name='categoria',
            field=models.CharField(choices=[('ESTRELA', 'Estrela'), ('NEBULOSA', 'Nebulosa'), ('GALAXIA', 'Galáxia'), ('PLANETA', 'Planeta')], default='', max_length=50),
        ),
    ]
